### ISSUE TITLE
New URL breaks the extension

### ISSUE THREAD

**Issue by jlnhlfan** [HEYimHeroic/MiiStudioMiiLoader#5]
The website mentioned in the extension is https://my.nintendo.com/mii

However, the url for the Mii Studio is now https://studio.mii.nintendo.com/?client_id=b2486001c0980130 (or whatever is after the = sign)

This completely breaks the extension, rendering it unusable. Is there any way to fix this, or is this extension done for?

**Comment by HEYimHeroic** [comment]
the https://my.nintendo.com/mii link works perfectly fine still, exactly as it always has. the link will not work unless you are signed into your Nintendo account at My Nintendo. if you are not signed in, it will redirect you to the My Nintendo homepage after you sign in. all you need to do from this point is visit the https://my.nintendo.com/mii link again and it will take you to the Mii Studio. the descriptions for the Mii Studio Mii Loader extensions all clearly tell you to be logged in already.

i link to https://my.nintendo.com/mii instead of https://studio.mii.nintendo.com directly, because visiting https://studio.mii.nintendo.com when you are not signed in will _not_ redirect you anywhere. it will just display an error message, which confuses people. by linking to https://my.nintendo.com/mii, then logged in people will be taken to the Mii Studio, and logged out people will simply log in on the My Nintendo page it takes you to, and likely try using the https://my.nintendo.com/mii link again, where it will then work.

**Comment by jlnhlfan** [comment]
![image](https://github.com/user-attachments/assets/6f87a40d-8139-46b6-a261-beb86192dc43)
Then explain the URL I get when I click on that link.
